# .github/workflows/perf-test.yml
name: K6 Perf Test

on:
  pull_request:
    branches: [develop]
  push:
    branches: [main]

jobs:
  perf-test:
    runs-on: ubuntu-latest

    container:
      image: grafana/k6:latest
      options: --user 1001:1001

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run K6 smoke test
        run: |
          k6 run first-script.js
