name: k6 Load Test - docker image

on:
  push:
    branches:
      - "**"

jobs:
  run-test:
    runs-on: ubuntu-latest
    container:
      image: grafana/k6:latest
      options: --user root

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run k6 test
        uses: grafana/run-k6-action@v1
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
        with:
          path: first-script.js
